name: Fail

on:
  workflow_dispatch:

  merge_group:
    types: [checks_requested]


jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .
  
  # Fail "myjob" with run: false
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: false

  # trigger_workflow_other_repo:
  #   uses: bszeti/actions/.github/workflows/myworkflow.yaml@main
    