name: Fail

on:
  workflow_dispatch:

  # see https://medium.com/@kojoru/how-to-set-up-merge-queues-in-github-actions-59381e5f435a
  # Note
  # error: GH006: Protected branch update failed for refs/heads/test.
  # A pull request for this branch has been added to a merge queue. Branches that are queued for merging cannot be updated. To modify this branch, dequeue the associated pull request.
  merge_group:


jobs:
  # event:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - env:
  #         EVENT_CONTEXT: ${{ toJSON(github.event) }}
  #       run: |
  #         echo $EVENT_CONTEXT | jq .
  
  # Fail "myjob" with run: false
  status-checks:
    runs-on: ubuntu-latest
    steps:
      # - if: contains(github.event.pull_request.title , 'fail')
      - run: |
          echo "Creating artifact..."
          sleep 10
          echo "Done"
      - if: contains(github.event.merge_group.head_commit.message , 'fail')
        run: |
          echo "::error ::Failing...."
          exit 1


    