name: Fail

on:
  workflow_dispatch:

  # see https://medium.com/@kojoru/how-to-set-up-merge-queues-in-github-actions-59381e5f435a
  merge_group:


jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .
  
  # Fail "myjob" with run: false
  myjob:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.pull_request.title , 'fail')
        run: |
          echo "::error :: Failing...."

  # trigger_workflow_other_repo:
  #   uses: bszeti/actions/.github/workflows/myworkflow.yaml@main
    