name: Fail

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - opened
  #     - enqueued
  merge_group:
    types: [checks_requested]


jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .
      # Fail run
      - run: false

  # trigger_workflow_other_repo:
  #   uses: bszeti/actions/.github/workflows/myworkflow.yaml@main
    