name: Pull request

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  # pull_request:
  #   branches: ['*']
  #   types:
  #     # - closed
  #     - assigned
  #     - unassigned
  #     - labeled
  #     - unlabeled
  #     - opened
  #     - edited
  #     - closed
  #     - reopened
  #     - synchronize
  #     - converted_to_draft
  #     - locked
  #     - unlocked
  #     - enqueued
  #     - dequeued
  #     - milestoned
  #     - demilestoned
  #     - ready_for_review
  #     - review_requested
  #     - review_request_removed
  #     - auto_merge_enabled
  #     - auto_merge_disabled
  # push:
  #   branches: ['*']


jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .
      # Fail run
      - run: false

  # trigger_workflow_other_repo:
  #   uses: bszeti/actions/.github/workflows/myworkflow.yaml@main
    