name: Pull request

on:
  workflow_dispatch:
  pull_request:

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .
      - uses: actions/checkout@v4
      - name: Try gh cli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr view ${{ github.event.pull_request.number }}
          gh pr view ${{ github.event.pull_request.number }} --json files | jq .

  # We don't fail "myjob" here
  validation:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running validation."
          sleep 3
          echo "Done"

    
