name: Pull request review

on:
  workflow_dispatch:
  pull_request_review:

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .

  pipeline:
    runs-on: ubuntu-latest
    if: github.event_name=='workflow_dispatch' || github.event.review.state == 'approved'
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      # Check changed files
      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
             **/*.json
      - name: List all changed files 1
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  myjob:
    runs-on: ubuntu-latest
    needs: pipeline
    steps:
      - name: List all changed files 2
        env:
          ALL_CHANGED_FILES: ${{ jobs.pipeline.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      # Build...
      - if: jobs.pipeline.outputs.any_changed == 'true'
        run: |
          echo "Creating artifact..."
          sleep 10
          echo "Done"
      - if: steps.changed-files.outputs.any_changed == 'true' && contains(github.event.pull_request.title , 'fail')
        run: |
          echo "::error ::Failing...."
          exit 1
