name: Pull request enqueue

on:
  workflow_dispatch:
  pull_request:
    paths: 
    - '**.json'
    types:
      # - enqueued
      - closed
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - locked
      - unlocked
      - enqueued
      - dequeued
      - milestoned
      - demilestoned
      - ready_for_review
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .

  # We don't fail "myjob" here
  pipeline-test:
    runs-on: ubuntu-latest
    # if: github.event.review.state == 'approved'
    steps:
      - run: |
          echo "Creating artifact..."
          sleep 1
          echo "Done"
      - if: contains(github.event.pull_request.title , 'fail')
        run: |
          echo "::error ::Failing...."
          exit 1

    
