name: Pull request

on:
  workflow_dispatch:
  pull_request:
    branches: ['*']
    type:
    - closed
    # types:
    #   - closed
  # push:
  #   branches: ['*']


jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  trigger_workflow_other_repo:
    uses: bszeti/actions/.github/workflows/myworkflow.yaml@main
    