name: Pull request review

on:
  workflow_dispatch:
  pull_request_review:

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .

  # We don't fail "myjob" here
  pipeline:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # with:
        #   files: |
        #      **.json

      - name: List all changed files markdown files
        # if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: |
          echo "Creating artifact..."
          sleep 10
          echo "Done"
      - if: contains(github.event.pull_request.title , 'fail')
        run: |
          echo "::error ::Failing...."
          exit 1

    
