name: Pull request

on:
  workflow_dispatch:
  pull_request_review:
    xx:

jobs:
  # event:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - env:
  #         EVENT_CONTEXT: ${{ toJSON(github.event) }}
  #       run: |
  #         echo $EVENT_CONTEXT | jq .

  # We don't fail "myjob" here
  pipeline:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - run: |
          echo "Creating artifact..."
          sleep 10
          echo "Done"
      - if: contains(github.event.pull_request.title , 'fail')
        run: |
          echo "::error ::Failing...."
          exit 1

    
