name: Pull request

on:
  workflow_dispatch:
  pull_request:
env:
  FILE_FILTER_REGEXP: ".*json"

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .
      - uses: actions/checkout@v4
      - name: Try gh cli
        id: gh_changed_files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo ${{ github.event.pull_request.url.html.href }}
          # gh pr view ${{ github.event.pull_request.self.href }}
          gh pr view ${{ github.event.pull_request.html.href }} --json files
          # gh pr view ${{ github.event.pull_request.number }} --json files 
          
          changed_files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files.[].path | select(test("${{env.FILE_FILTER_REGEXP}}"))')
          echo changed_files=$changed_files | tee -a $GITHUB_OUTPUT
          
          any_changed=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '[ .files.[].path | test("${{env.FILE_FILTER_REGEXP}}") ] | any')
          echo any_changed=$any_changed | tee -a $GITHUB_OUTPUT
      - if: ${{ steps.gh_changed_files.outputs.any_changed == 'true' }}
        run: |
          echo "any_changed is true"
          echo ${{ steps.gh_changed_files.outputs.changed_files }}
        
          
      # - if: ${{ contains(steps.gh_changed_files.outputs.changed_files, 'test.json') }}
      #   run: |
      #     echo "Yes"
      #     echo ${{ steps.gh_changed_files.outputs.changed_files }}
        

  # We don't fail "myjob" here
  validation:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running validation."
          sleep 3
          echo "Done"

    
# cat <<EOF | jq '[ .files.[].path | select(test(".*json")) ]'
# cat <<EOF | jq '[ .files.[].path | test(".*json")? ] | any'